### ISSUE TITLE
Pixudi

### ISSUE THREAD

**Issue by ddarkwing** [scrtlabs/Grants#97]
![](https://user-images.githubusercontent.com/91618941/223704798-1b441ae3-cd40-4641-9147-e8b43f57e497.png)

![](https://user-images.githubusercontent.com/91618941/224052419-d03e0ef3-f1ad-4eeb-85aa-bbd2078be949.png)
Pixudi is a blockchain-based board game where players compete to collect treasures by overcoming obstacles and completing missions. The game includes unique scenarios, mechanics, treasures, and adventures. Pixudi aims to introduce blockchain technology to millions of users and bridge the gap between traditional board games and NFT games. The game will be available on web, Nintendo Switch, mobile devices, and physical copies. NFTs include boards, characters, items, and pets, which can be traded and purchased on the Pixudi Marketplace. The game mechanics involve rolling dice and moving characters on different boards with various effects, including fights, mini-games, and shops. The board is interactive: with skins, pets, and in-game items come handy but players cannot buy the victory.

![](https://user-images.githubusercontent.com/91618941/224053036-a2fd40e9-e832-40c3-8d8d-64fb5f3141cd.png)
LOW TRUST:  like in centralised services, they depend on the networks and blockchains in which they are launched.
For example, the Solana blockchain has stopped several times in history, and thus, when the network stops, it stops all services.
GAP BETWEEN CRYPTO AND REAL WORLD: there is little to no connection between GameFi projects and the market of real board games while most traditional gamers don’t like or don’t understand NFTs and crypto
Solution
PLAY-TO-EARN IS GETTING OLD: players who professionally participate in tournaments on well-known games already have the opportunity to earn money, and such a mechanic is similar to scam and stops the audience of ordinary players from getting acquainted with the world of blockchain games.
ONCE AGAIN, THE GAP: Nintendo Switch and other consoles are looking for an opportunity to enter the blockchain industry.
Key board game manufacturers are looking for new ways to interact with customers
NOT USER-FRIENDLY: Most of the blockchain games aren’t deep enough for long-term engagement
ISOLATION: Existing games are built on just one blockchain with no connection to other games / blockchains

![](https://user-images.githubusercontent.com/91618941/224053169-1a7bd85b-5dbd-408b-bbb7-6695bebaed98.png)
We use blockchain technology to create an advanced and transparent game. But in order to provide the best game experience for our users and protect them from network failures, all the main game elements are duplicated in our database using one-way synchronisation technology.
The connection between real/virtual is established by the fusion of the online platform and its physical copy + Nintendo Switch version. Users can play Pixudi alone on their device as well as together with friends in a pub.
Play-to-Collect is our choice! It is close in spirit to traditional gamers and yet does not exclude the opportunity to earn money on our tournaments and competitions.
Nintendo Switch version of Pixudi will be released to attract broader audience
We will establish partnerships with board game manufacturers to help them become part of the blockchain industry
Pixudi uses a Free-to-Play business model (Nintendo Switch model will be slightly modified) so the users can play for free and pay for additional features.
Pixudi already is multichain. We have developed customizable cross-chain bridge solution for transferring NFT objects from one blockchain to another

![](https://user-images.githubusercontent.com/91618941/224053345-96dca6b3-4e6b-4a13-b368-84a27765ccce.png)
![](https://user-images.githubusercontent.com/91618941/224053673-6b81553b-d846-46f0-889e-b40b50328209.png)
Pixudi follows the free-to-play model, allowing players to get acquainted with the game with zero friction. The browser game will be released together with the marketplace where users will be able to buy NFT items to improve their gaming experience.
We are creating a bridge between the traditional board game audience and the blockchain world, thus Secret Network will become the main blockchain for this task.
New games coming into the Pixudi, issuing their tokens on the Secret Network blockchain, and gamers who can transfer NFTs from other blockchains, will generate new transactions on the Secret Network blockchain, contributing to the growth of the entire ecosystem.
For example, holders of premium NFTs, the physical versions of the games will be released just like a regular board game. Users will be able to buy one of 10 sets with an unique map, character miniatures, sticker set and a coupon with a code to get the exact same set in the browser game. Thus, a strong connection is established between the real and virtual world of the NFT.
The Secret Network ecosystem can be the best entry point into the world of the Board Game NFT industry and manufacturers in games for large masses of new audiences ready to switch their activities from traditional games.
All processes that determine such processes as a dice roll and a player's move are implemented through smart contracts, which increases the trust and purposeful use of the blockchain as a decentralized process without the possibility of hacking.

![](https://user-images.githubusercontent.com/91618941/224054001-cd942893-4373-44e0-a498-674aa7b563fd.png)
**Web Version**
The first version of the game to be released. You can already test the gameplay and marketplace now! Contact us for more details.
**Nintendo Switch**
Console version is our second priority. Pixudi will be the first blockchain game ever built on that platform via synchronisation API.
**Mobile Version**
Mobile games are a half of the gaming market, so we will be releasing a mobile version (iOS and Android) of Pixudi in  Q4 ‘24.
**Physical Copy**
Pixudi Box containing board, figures, sticker packs, collectible cards and other items is coming in Q4 ‘24.

![](https://user-images.githubusercontent.com/91618941/224049862-8c60f59a-82e2-45d1-aba8-259dcc002dbe.png)
![](https://user-images.githubusercontent.com/91618941/224059149-1a0041ef-a74e-4155-bd96-cb8f09c01e0e.png)
![](https://user-images.githubusercontent.com/91618941/224059271-68db8b58-6ad5-4d34-b4a9-ce98cae73a04.png)
![](https://user-images.githubusercontent.com/91618941/224059353-89b08e7d-3269-4666-a682-0b62906487df.png)

## Value capture for Secret Network ecosystem
The main KPIs for Secret Network is TVL (privacy value add to other blockchain ecosystems), number of transactions and number of user (for applications)

![](https://user-images.githubusercontent.com/91618941/223683647-80203a47-b95f-4202-9594-4c3149036a79.png)
![Alex (5)](https://user-images.githubusercontent.com/91618941/223725200-6a95fd15-3c68-448e-9862-ecd4af313ed0.png) ![Eugene](https://user-images.githubusercontent.com/91618941/223723498-83d03a77-f181-4f25-8676-b4fc3dab8d3b.png) ![Katya](https://user-images.githubusercontent.com/91618941/223732734-2dd93fe1-7646-4c2c-b328-40b987864974.png) ![Nikki](https://user-images.githubusercontent.com/91618941/223732785-3b35ca20-20d1-4161-9951-e42c6a9ceb1d.png) ![Max](https://user-images.githubusercontent.com/91618941/223732820-06d6f7fa-e458-40a3-8adc-168e3e8bd4b0.png) ![Dan](https://user-images.githubusercontent.com/91618941/223732856-66079d47-fcb0-42e0-9db1-b4c6e3d457d0.png) ![Stephen](https://user-images.githubusercontent.com/91618941/223732905-3fe7e2ee-51cd-4acc-bd2e-44266671a368.png) ![Zehan](https://user-images.githubusercontent.com/91618941/223732953-fad88fe5-37b7-4522-a832-df5e32f9b3f0.png) ![Ashley](https://user-images.githubusercontent.com/91618941/223733007-a607e24b-0795-4fa9-b899-4cf2530c497c.png)
![](https://user-images.githubusercontent.com/91618941/224051400-7cd1fec5-9df8-455f-9078-ec6bd983624c.png)
- ![Profile (2)](https://user-images.githubusercontent.com/91618941/223703782-7aa4e1cf-9a66-49a7-985d-e9bf2ebe8e33.png) **Contact Name:** Alex Scoresby
- ![Telegram](https://user-images.githubusercontent.com/91618941/223689479-8a84cef2-eac1-4a7a-b5fb-870032c542a9.png) **Contact telegram:** @ducktalesblock
- ![Discord (1)](https://user-images.githubusercontent.com/91618941/223690631-79a2d513-80a4-4849-8360-509d00db5775.png) **Contact discord:** Alex Scoresby#6447
- ![Mail](https://user-images.githubusercontent.com/91618941/223698121-af355250-3343-4b2d-8e42-acff904f0b0a.png) **Contact Email:** welcome@pixudi.com
- ![Logo small (1)](https://user-images.githubusercontent.com/91618941/223690230-41914ccb-6223-4334-9545-ca3ebab830b4.png) **Project Website:** https://pixudi.com
- ![Twitter](https://user-images.githubusercontent.com/91618941/223698416-0ac4b1de-f00d-4d39-ace2-87430ab5fee8.png) **Project twitter:** https://twitter.com/thepixudi
- ![Discord (1)](https://user-images.githubusercontent.com/91618941/223690631-79a2d513-80a4-4849-8360-509d00db5775.png) **Project discord:** https://discord.com/invite/W4QGHh9FRX
- ![Telegram](https://user-images.githubusercontent.com/91618941/223689479-8a84cef2-eac1-4a7a-b5fb-870032c542a9.png) **Project telegram:** https://t.me/pixudi
- ![Linkedin](https://user-images.githubusercontent.com/91618941/223697914-6f94292d-6216-499e-ba52-589004ed4ee7.png) **Project Linkedin:** https://www.linkedin.com/company/pixudi/
 
![Group 242 (3)](https://user-images.githubusercontent.com/91618941/223692002-26cfbab3-3e28-4cc4-83c2-f4ffb3b31f9d.png)

During development, we will partially upload parts of our project to open source, and upon individual request, we provide access to our repository. If you need access to view the code at the stage of work, we will gladly provide it. 

- https://github.com/kapcrew/pixudi_back
- https://github.com/kapcrew/pixudi_front

![](https://user-images.githubusercontent.com/91618941/223696771-50e003c6-9e6e-4817-96ab-ef20cfd12e86.png)

### Stage 1 Q3 2022 ![check 1 (1)](https://user-images.githubusercontent.com/91618941/223710920-eeb490de-36f0-448d-a08b-eecd8a6ec14b.png)

- **Duration:** 3 months

| **Number** | **Deliverable** |
|:----------:|---------------------------------|
|  1. | Game concept development |
|  2. | Start of litepaper creation |
|  3. | Market research |
|  4. | Art concept development |
|  5. | Launch of social media channels |
|  6. | Game logic development |
|  7. | Social media channels launch |
|  8. | Brand guidelines creation |

### Stage 2  Q4 2022 ![check 1 (1)](https://user-images.githubusercontent.com/91618941/223710920-eeb490de-36f0-448d-a08b-eecd8a6ec14b.png)
- **Duration:** 3 months
-
| **Number** | **Deliverable** |
|:----------:|----------------------------------------------------------------------|
|  1. | Season 1 preparation: story, scenario, first board (night and day version) |
|  2. | Creation of the Season 1 basic set of in-game items |
|  3. | Code for the generator |
|  4. | Creation of all components for generative characters and pets |
|  5. | Landing Page launch |
|  6. | Community development strategy |
|  7. | GTM Startegy |

### Stage 3 Q1 2023 (![In Progress](https://user-images.githubusercontent.com/91618941/223715790-c8749152-6881-4e2b-9126-f8c6e22204a6.png))
- **Duration:** 3 months

| **Number** | **Deliverable** |
|:----------:|-----------------|
| 1.| Game engine development |
| 2. | Game mechanics development |
| 3. | NFT Collection development: custom extension to ERC-21 standard, generative art, collection page  |
| 4. | Litepaper alpha release |
| 5. | Start of community development |
| 6. | Development of the guild structure |
| 7. | Blockchain integration |
| 8. | Lottery and betting preparation |
| 9. | Mini games development |

### Stage 4 Q2 2023
- **Duration:** 3 months

| **Number** | **Deliverable** |
|:----------:|-----------------|
| 1.| Alpha game release |
| 2. | Debugging |
| 3. | NFT Collection Launch |
| 4. | Marketplace Launch |
| 5. | Game testing by KOLs |
| 6. | Development of referral program |
| 7. | Lottery launch |
| 8. | Betting launch |
| 9. | Incorporation of 2 mini games into the board |

### Stage 5 Q3 2023
- **Duration:** 3 months

| **Number** | **Deliverable** |
|:----------:|-----------------|
| 1. | Game trailer release |
| 2. | In-game tournaments release |
| 3. | AMA Sessions launch |
| 4. | Mobile version start of development (Android & IOS) |
| 5. | Nintendo Switch version start of development |
| 6. | Refferal program launch |
| 7. | Mini games launch inside and outside the board |
| 8. | Guilds and DAO development |

### Stage 6 Q4 2023
- **Duration:** 3 months

| **Number** | **Deliverable** |
|:----------:|-----------------|
| 1. | KPI analysis |
| 2. | Mobile version continued development |
| 3. | Nintendo Switch version continued development |
| 4. | Interactive board release |
| 5. | Start of development of the physical board |
| 6. | Strategic partnerships |
| 7. | Season 2 preparation |
| 8. | Guilds and DAO launch |

We will require 3 months and $50,000 to launch the first stage of the game.

Pixudi follows the free-to-play model, allowing players to get acquainted with the game with zero friction. The browser game will be released together with the marketplace where users will be able to buy NFT items to improve their gaming experience.
New games coming into the Pixudi, issuing their tokens on the Secret Network blockchain, and gamers who can transfer NFTs from other blockchains, will generate new transactions on the Secret Network blockchain, contributing to the growth of the entire ecosystem.
For  example holders of premium NFTs, the physical versions of the games will be released just like a regular board game. Users will be able to buy one of 10 sets with a unique map, character miniatures, sticker set and a coupon with a code to get the exact same set in the browser game. Thus, a strong connection is established between the real and virtual world of the NFT.
The Secret Network ecosystem can be the best entry point into the world of the Board Game NFT industry and manufacturers in games for large masses of new audiences ready to switch their activities from traditional games.
All processes that determine such processes as a dice roll and a player's move are implemented through smart contracts, which increases the trust and purposeful use of the blockchain as a decentralised process without the possibility of hacking.

![](https://user-images.githubusercontent.com/91618941/224061864-14d85953-42b5-4fe7-9b87-96a7219f114c.png)
Remember how your family (together) or with friends gathered to play board games exactly the same feelings you will get from our project. You will find more in our presentation, enjoy watching and have a nice day)
Also we recommend you to watch our pitch deck: https://drive.google.com/file/d/1Js_VJnUMNXAszDvB5DnincH96RML2mwn/view?usp=share_link
![](https://user-images.githubusercontent.com/91618941/224061444-b568f766-4fc8-4765-9d37-630deb9e1aab.png)

**Comment by ertemann** [comment]
hey @ddarkwing thank you for submitting a grant! our Grant manager has been OOO for the past weeks and will be back halfway through may. feel free to get in contact with me in the meantime via: https://t.me/Ertemann or ertemann@scrt.agency
